name: 'skills_assessment_data_engineer'
version: '1.0.0'
config-version: 2

profile: 'skills_assessment_data_engineer'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  skills_assessment_data_engineer:
    staging:
      +schema: stg
      +materialized: view
